### ISSUE TITLE
matro7sh installed on havoc breaks other dependencies

### ISSUE THREAD

**Issue by p4p1** [matro7sh/matro7sh_loaders#3]
After installing 221b loaders inside of Havoc through the "Extention" tab after a reboot of the client front-end the python scripts crash all of the other modules see screenshot:
![image](https://github.com/matro7sh/matro7sh_loaders/assets/19672114/7bc08fe3-dafa-4340-bf5b-1a94ed3ae314)
This is caused by the modules added through Extensions / Script Manager beeing loaded before the other client scripts that are hard coded inside of the client. The 221b script does a chdir that breaks the other modules:
![image](https://github.com/matro7sh/matro7sh_loaders/assets/19672114/613d0ed4-dce9-4b6f-b71a-0d24243e2571)
screenshot of /matro7sh_221b.py

**Comment by djnnvx** [comment]
done in 3d2a29e. I'll close this issue once you confirm this is OK for you.

**Comment by p4p1** [comment]
I just checked it has been fixed thank you so much :)
